<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <base href="/" />
    <link rel="stylesheet" type="text/css" href="/css/master.css" />
    <link rel="stylesheet" type="text/css" href="/css/admin.css" />
    <script src="/js/form.js"></script>
  </head>
  <body>
    <div id="header">
      <div id="logo">
        <img src="/images/logo-admin.gif" />
      </div>
      
      <div id="menu">
        <?php if (Zend_Auth::getInstance()->hasIdentity()): ?>
        <a href="<?php echo $this->url(array(), 'admin-catalog-index'); ?>">CATALOG</a>
        <a href="<?php echo $this->url(array(), 'logout'); ?>">LOGOUT</a>
        <?php else: ?>
        <a href="<?php echo $this->url(array(), 'login'); ?>">LOGIN</a>
        <?php endif; ?>
      </div>
    </div>
    
    <div id="content">
      <?php echo $this->layout()->content ?>
    </div>
    
    <div id="footer">
      <p>Created with <a href="http://framework.zend.com/">Zend Framework</a>. Licensed under <a href="http://www.creativecommons.org/">Creative Commons</a>.</p>
    </div>   
    	<div>
	<a href="<?php echo $this->url(array(), 'home'); ?>">Home</a><br />
	<a href="<?php echo $this->url(array('page' => 'about-us'), 'static-content'); ?>">Über uns</a><br />
	<a href="<?php echo $this->url(array('page' => 'services'), 'static-content'); ?>">SERVICES</a><br />
	<a href="<?php echo $this->url(array(), 'contact'); ?>">Contact</a><br />
	<a href="<?php echo $this->url(array('id' => '1'), 'catalog-display'); ?>">Artikel 1</a><br />
	<a href="<?php echo $this->url(array(), 'admin-catalog-index'); ?>">Artikel Übersich</a><br />
	<a href="<?php echo $this->url(array('id' => '1'), 'admin-catalog-display'); ?>">Artikel 1 - Admin</a><br />		
	<a href="<?php echo $this->url(array(), 'login'); ?>">Admin Login</a><br />
	</div> 
  </body>
</html>
