<h2>View Item</h2>
<h3>
  FOR SALE: 
  <?php echo $this->escape($this->item->title); ?> - 
  <?php echo $this->escape($this->item->year); ?> - 
  <?php echo $this->escape($this->item->grade); ?>
</h3>

<div id="container">
  <div id="record">  
    <table>
      <tr>
        <td class="key">Title:</td>
        <td class="value">
          <?php echo $this->escape($this->item->title); ?>
        </td>
      </tr>
      <tr>
        <td class="key">Type:</td>
        <td class="value">
          <?php echo $this->escape(
            $this->item->type); ?>
        </td>
      </tr>
      <tr>
        <td class="key">Year:</td>
        <td class="value">
          <?php echo $this->escape($this->item->year); ?>
        </td>
      </tr>
      <tr>
        <td class="key">Country:</td>
        <td class="value">
          <?php echo $this->escape(
            $this->item->country->name); ?>
        </td>
      </tr>
      <tr>
        <td class="key">Denomination:</td>
        <td class="value">
          <?php echo $this->escape(
            sprintf('%01.2f', $this->item->denomination)); ?>
        </td>
      </tr>
      <tr>
        <td class="key">Grade:</td>
        <td class="value">
          <?php echo $this->escape(
            $this->item->grade); ?>
        </td>
      </tr>
      <tr>
        <td class="key">Sale price:</td>
        <td class="value">
          $<?php echo $this->escape($this->item->salepricemin); ?> - 
          $<?php echo $this->escape($this->item->salepricemax); ?>
        </td>
      </tr>
      <tr>
        <td class="key">Description:</td>
        <td class="value">
          <?php echo $this->escape($this->item->description); ?>
        </td>
      </tr>
      <tr>
        <td class="key">Seller:</td>
        <td class="value">
          <?php echo $this->escape($this->item->sellername); ?>
          (<?php echo $this->escape($this->item->selleremail); ?>)
          <br/>
          <?php echo $this->escape($this->item->selleraddress); ?>
          <br/>
          <?php echo $this->escape($this->item->sellerphone); ?> 
        </td>
      </tr>        
    </table>
  </div>  
</div>
