<h2>List Items</h2>
<!-- TODO: Change this from records -->
<?php if (count($this->stampItems)): ?>
<div id="records">
  <form method="post" action="<?php echo $this->url(array(), 'admin-catalog-delete'); ?>">
    <table>
      <tr>
        <td></td>    
        <td class="key">
          Item ID
        </td>
        <td class="key">
          Title
        </td>
        <td class="key">
          Denomination
        </td>
        <td class="key">
          Country
        </td>
        <td class="key">
          Grade
        </td>
        <td class="key">
          Year
        </td>    
        <td></td>    
        <td></td>    
      </tr>
      <?php foreach ($this->stampItems as $item):?>
      <tr>
        <td><input type="checkbox" name="ids[]" value="<?php echo $item->id; ?>" style="width:2px" /></td>
        <td><?php echo $this->escape($item->id); ?></td>
        <td><?php echo $this->escape($item->title); ?></td>
        <td><?php echo $this->escape(sprintf('%1.2f', $item->denomination)); ?></td>
        <td><?php echo $this->escape($item->country->name); ?></td>
        <td><?php echo $this->escape($item->grade); ?></td>
        <td><?php echo $this->escape($item->year); ?></td>    
        <td><a href="<?php echo $this->url(array('id' => $item->id), 'admin-catalog-display'); ?>">Display</a></td>    
        <td><a href="<?php echo $this->url(array('id' => $item->id), 'admin-catalog-update'); ?>">Update</a></td>    
      </tr>  
      <?php endforeach; ?>
      <tr>
        <td colspan="9"><input type="submit" name="submit" style="width:150px" value="Delete Selected" /></td>
      </tr>    
    </table>
  </form>
</div>

<?php else: ?>
No records found - hab nüscht gefunden!!
<?php endif; ?>
