//TODO: This needs to be changed to work with Doctrine 2. Maybe a viewhelper is in order?
<h2>View Item</h2>
<h3>
  FOR SALE: 
  <?php echo $this->escape($this->item['Title']); ?> - 
  <?php echo $this->escape($this->item['Year']); ?> - 
  <?php echo $this->escape($this->item['Square_Model_Grade']['GradeName']); ?>
</h3>

<div id="container">
  <div id="record">  
    <table>
      <tr>
        <td class="key">Title:</td>
        <td class="value">
          <?php echo $this->escape($this->item['Title']); ?>
        </td>
      </tr>
      <tr>
        <td class="key">Type:</td>
        <td class="value">
          <?php echo $this->escape(
            $this->item['Square_Model_Type']['TypeName']); ?>
        </td>
      </tr>
      <tr>
        <td class="key">Year:</td>
        <td class="value">
          <?php echo $this->escape($this->item['Year']); ?>
        </td>
      </tr>
      <tr>
        <td class="key">Country:</td>
        <td class="value">
          <?php echo $this->escape(
            $this->item['Square_Model_Country']['CountryName']); ?>
        </td>
      </tr>
      <tr>
        <td class="key">Denomination:</td>
        <td class="value">
          <?php echo $this->escape(
            sprintf('%01.2f', $this->item['Denomination'])); ?>
        </td>
      </tr>
      <tr>
        <td class="key">Grade:</td>
        <td class="value">
          <?php echo $this->escape(
            $this->item['Square_Model_Grade']['GradeName']); ?>
        </td>
      </tr>
      <tr>
        <td class="key">Sale price:</td>
        <td class="value">
          $<?php echo $this->escape($this->item['SalePriceMin']); ?> - 
          $<?php echo $this->escape($this->item['SalePriceMax']); ?>
        </td>
      </tr>
      <tr>
        <td class="key">Description:</td>
        <td class="value">
          <?php echo $this->escape($this->item['Description']); ?>
        </td>
      </tr>
    </table>
  </div>  
</div>

